(()=>{'use strict';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);
const n=Number(params.get('seed')),day=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});
let seed=Number.isInteger(n)&&n>0&&n<=4294967295?n:hash(day),target=null,last=null,playing=false,muted=true,audio=null,eventTimer,toastTimer;
const beat=Number(params.get('beat'));if(params.has('beat')&&Number.isFinite(beat)&&beat>=0&&beat<=100000)target=Math.floor(beat);
function hash(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0||1}
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3000)}
function sound(type){if(muted)return;try{audio ||=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.setValueAtTime(type==='star'?660:type==='end'?150:360,audio.currentTime);o.frequency.exponentialRampToValueAtTime(type==='star'?1100:70,audio.currentTime+.13);g.gain.setValueAtTime(.065,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.start();o.stop(audio.currentTime+.2)}catch{}}
function event(s){if(typeof s==='object'){sound(s.type);s=s.message||s.text||''}else if(s==='star'||s==='collect'){sound('star');return}if(!s)return;$('event').textContent=s;$('event').classList.add('show');clearTimeout(eventTimer);eventTimer=setTimeout(()=>$('event').classList.remove('show'),1900)}
function challenge(){if(target!==null){$('challenge').hidden=false;$('challenge').innerHTML='朋友发来挑战：<b>'+target+' 分</b>。同一张图，看看谁更会转地球。';$('start').innerHTML='接下这局挑战 <span>↗</span>'}else{$('challenge').hidden=true}}
const game=new window.EchoGame($('game'),{onUpdate(s){$('score').textContent=String(s.score).padStart(4,'0');$('time').textContent=Math.max(0,s.timeLeft).toFixed(1);$('stars').textContent='✦ '+s.stars;$('status').textContent=`第 ${s.level||1} / 3 关 · 按住左右两边转动世界`},onEnd:finish,onEvent:event});
function start(){last=null;playing=true;document.body.classList.add('playing');$('intro').hidden=true;$('result').hidden=true;$('share-fallback').hidden=true;$('restart').hidden=false;$('new-map').hidden=true;$('event').classList.remove('show');clearTimeout(eventTimer);sound('start');game.start(seed);$('game').focus({preventScroll:true})}
function finish(r){if(!playing)return;playing=false;last=r;document.body.classList.remove('playing');$('restart').hidden=true;$('new-map').hidden=false;$('event').classList.remove('show');sound('end');const survived=r.reason==='survived';
let best=r.score;try{best=Math.max(r.score,Number(localStorage.getItem('tilt-best-'+seed))||0);localStorage.setItem('tilt-best-'+seed,String(best))}catch{}
$('result-title').textContent=survived?'下班了！地球归你管':'地球还没转明白';$('result-subtitle').textContent=survived?'三个房间全部逃脱，你就是重力管理员。':'再转一点点，也许出口就在下一个角度。';$('result-score').textContent=r.score;$('result-time').textContent=r.elapsed.toFixed(1)+' 秒';$('result-stars').textContent=r.stars+' 颗';$('best').textContent=best+' 分';$('result-rank').textContent=survived?'重力管理员':(r.levels||0)>=2?'旋转高手':'地球实习生';
$('comparison').hidden=target===null;if(target!==null)$('comparison').textContent=r.score>target?'你超过朋友 '+(r.score-target)+' 分！把挑战发回去。':r.score===target?'和朋友打平了，再来一局决胜负。':'还差 '+(target-r.score)+' 分超过朋友。';$('result').hidden=false;$('status').textContent=survived?'下班成功！你把地球转明白了':'时间到了！再转一次试试。'}
function link(){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('seed',String(seed));u.searchParams.set('beat',String(last?.score||0));return u.href}
async function share(){if(!last)return;const url=link(),text=`我在《地球歪了》闯过${last.levels||0}关，拿下${last.score}分。你不能动小球，只能转动整个世界！同一张图你能赢我吗？`;
if(navigator.share){try{await navigator.share({title:'地球歪了 · 朋友挑战',text,url});return}catch(e){if(e.name==='AbortError')return}}
try{await navigator.clipboard.writeText(text+'\n'+url);toast('挑战链接已复制，发给朋友来应战！')}catch{$('share-fallback').hidden=false;$('share-url').value=url;$('share-url').focus();$('share-url').select();toast('长按下方链接即可复制')}}
function card(){if(!last)return;const c=document.createElement('canvas');c.width=900;c.height=1200;const ctx=c.getContext('2d');ctx.fillStyle='#171523';ctx.fillRect(0,0,900,1200);for(let y=0;y<1200;y+=35)for(let x=0;x<900;x+=35){ctx.fillStyle='#ffffff0b';ctx.fillRect(x,y,2,2)}ctx.textAlign='left';ctx.fillStyle='#b994ff';ctx.font='bold 23px sans-serif';ctx.fillText('TILT / 重力成绩单',75,100);ctx.fillStyle='#f6f3ed';ctx.font='900 66px sans-serif';ctx.fillText('地球歪了',75,213);ctx.font='30px sans-serif';ctx.fillStyle='#b4afc7';ctx.fillText('球不听你的，重力听。',75,278);ctx.fillStyle='#d9ff70';ctx.font='900 200px sans-serif';ctx.fillText(String(last.score),63,523);ctx.font='bold 32px sans-serif';ctx.fillText('分',76,590);ctx.fillStyle='#f6f3ed';ctx.font='36px sans-serif';ctx.fillText(`用时 ${last.elapsed.toFixed(1)} 秒 / 星星 ${last.stars} 颗`,75,686);ctx.strokeStyle='#625174';ctx.setLineDash([8,10]);ctx.beginPath();ctx.moveTo(75,744);ctx.lineTo(825,744);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d9ff70';ctx.beginPath();ctx.roundRect(75,810,750,115,24);ctx.fill();ctx.fillStyle='#202619';ctx.font='bold 35px sans-serif';ctx.fillText('不服？点挑战链接，把地球转明白。',100,882);ctx.fillStyle='#b994ff';ctx.font='25px sans-serif';ctx.fillText('45秒一局 · 手机电脑打开就玩',75,1020);ctx.fillStyle='#91869e';ctx.font='19px sans-serif';ctx.fillText('把战绩图和挑战链接一起发给朋友',75,1080);c.toBlob(blob=>{if(!blob){toast('图片生成失败，请重试');return}const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='地球歪了-'+last.score+'分.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('战绩图已生成，再复制挑战链接一起发')},'image/png')}
$('start').onclick=start;$('again').onclick=start;$('restart').onclick=()=>{game.stop();start()};$('share').onclick=share;$('save').onclick=card;$('sound').onclick=()=>{muted=!muted;$('sound').textContent='声音 '+(muted?'关':'开');$('sound').setAttribute('aria-label',muted?'开启声音':'关闭声音');$('sound').setAttribute('aria-pressed',String(!muted));sound('start')};$('new-map').onclick=()=>{seed=(Date.now()^Math.floor(Math.random()*4294967295))>>>0||1;target=null;last=null;history.replaceState(null,'',location.pathname+'?seed='+seed);challenge();$('intro').hidden=false;$('result').hidden=true;$('start').innerHTML='转动地球 <span>↗</span>';$('score').textContent='0000';$('time').textContent='45.0';$('stars').textContent='✦ 0';$('status').textContent='一张新地图 · 新的重力谜题';toast('新重力地图准备好了')};challenge();
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){game.stop();playing=false;document.body.classList.remove('playing');$('intro').hidden=false;$('result').hidden=true;$('restart').hidden=true;$('new-map').hidden=false;$('start').innerHTML='重新出发 <span>↗</span>';toast('已离开游戏，本局已结束，随时重新出发')}});
})();
