(()=>{'use strict';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);
const gameRegion=document.querySelector('.game-wrap');
function permitsSelection(target){return target instanceof Element&&!!target.closest('input,textarea,[contenteditable="true"]')}
for(const type of ['selectstart','contextmenu'])gameRegion.addEventListener(type,e=>{if(!permitsSelection(e.target))e.preventDefault()});
for(const control of [$('game'),$('brake')]){
  for(const type of ['touchstart','touchmove'])control.addEventListener(type,e=>{if(e.cancelable)e.preventDefault()},{passive:false});
  control.addEventListener('pointerdown',()=>{const selection=window.getSelection();if(selection&&!selection.isCollapsed)selection.removeAllRanges()});
}
const n=Number(params.get('seed')),day=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});
let seed=Number.isInteger(n)&&n>0&&n<=4294967295?n:hash(day),target=null,last=null,playing=false,muted=true,audio=null,eventTimer,toastTimer;
const beat=Number(params.get('beat'));if(params.get('v')==='2'&&params.has('beat')&&Number.isFinite(beat)&&beat>=0&&beat<=100000)target=Math.floor(beat);
function hash(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0||1}
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3000)}
function sound(type){if(muted)return;try{audio ||=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.setValueAtTime(type==='star'?660:type==='end'?150:360,audio.currentTime);o.frequency.exponentialRampToValueAtTime(type==='star'?1100:70,audio.currentTime+.13);g.gain.setValueAtTime(.065,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.start();o.stop(audio.currentTime+.2)}catch{}}
function event(s){if(typeof s==='string')sound(s.includes('星')?'star':'start');if(typeof s==='object'){sound(s.type);s=s.message||s.text||''}else if(s==='star'||s==='collect'){sound('star');return}if(!s)return;$('event').textContent=s;$('event').classList.add('show');clearTimeout(eventTimer);eventTimer=setTimeout(()=>$('event').classList.remove('show'),1900)}
function challenge(){if(target!==null){$('challenge').hidden=false;$('challenge').innerHTML='朋友发来挑战：<b>'+target+' 分</b>。同一张图，看看谁更会转地球。';$('start').innerHTML='接下这局挑战 <span>↗</span>'}else{$('challenge').hidden=true}}
const game=new window.EchoGame($('game'),{onUpdate(s){$('score').textContent=String(s.score).padStart(4,'0');$('time').textContent=Math.max(0,s.timeLeft).toFixed(1);$('stars').textContent='✦ '+s.stars;$('status').textContent=`第 ${s.level||1} / 6 关 · ${s.hasKey?(s.keyCollected?'钥匙到手':'先找钥匙'):'找到出口'}`;updateMission(s)},onEnd:finish,onEvent:event});
function start(){paused=false;$('brake').disabled=false;$('help').disabled=true;last=null;playing=true;document.body.classList.add('playing');$('intro').hidden=true;$('result').hidden=true;$('share-fallback').hidden=true;$('restart').hidden=false;$('new-map').hidden=true;$('event').classList.remove('show');clearTimeout(eventTimer);sound('start');game.start(seed);$('game').focus({preventScroll:true})}
function finish(r){if(!playing)return;paused=false;$('brake').disabled=true;$('help').disabled=false;brake(false);playing=false;last=r;document.body.classList.remove('playing');$('restart').hidden=true;$('new-map').hidden=false;$('event').classList.remove('show');sound('end');const survived=r.reason==='survived';
let best=r.score;try{best=Math.max(r.score,Number(localStorage.getItem('tilt-v2-best-'+seed))||0);localStorage.setItem('tilt-v2-best-'+seed,String(best))}catch{}
$('result-title').textContent=survived?'桃桃回家了！':'桃桃还在等你救援';$('result-subtitle').textContent=survived?'六座空间站全部通过，桃桃终于回家了。':'在危险区前刹车，等机关熄灭再通过。';$('result-score').textContent=r.score;$('result-levels').textContent=(r.levels||0)+' / 6';$('result-time').textContent=r.elapsed.toFixed(1)+' 秒';$('result-stars').textContent=r.stars+' 颗';$('best').textContent=best+' 分';$('result-rank').textContent=survived?'星际领航员':(r.levels||0)>=2?'虫洞冒险家':'见习宇航员';
$('comparison').hidden=target===null;if(target!==null)$('comparison').textContent=r.score>target?'你超过朋友 '+(r.score-target)+' 分！把挑战发回去。':r.score===target?'和朋友打平了，再来一局决胜负。':'还差 '+(target-r.score)+' 分超过朋友。';$('result').hidden=false;$('status').textContent=survived?'下班成功！你把地球转明白了':'时间到了！再转一次试试。'}
function link(){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('v','2');u.searchParams.set('seed',String(seed));u.searchParams.set('beat',String(last?.score||0));return u.href}
async function share(){if(!last)return;const url=link(),text=`我带桃桃闯过${last.levels||0}/6座空间站，拿下${last.score}分！《地球歪了2.0》有传送门、钥匙和激光。同一张图，你能赢我吗？`;

try{await navigator.clipboard.writeText(text+'\n'+url);toast('挑战链接已复制，发给朋友来应战！')}catch{$('share-fallback').hidden=false;$('share-url').value=url;$('share-url').focus();$('share-url').select();toast('长按下方链接即可复制')}}
function card(){if(!last)return;const c=document.createElement('canvas');c.width=900;c.height=1200;const ctx=c.getContext('2d');ctx.fillStyle='#171523';ctx.fillRect(0,0,900,1200);for(let y=0;y<1200;y+=35)for(let x=0;x<900;x+=35){ctx.fillStyle='#ffffff0b';ctx.fillRect(x,y,2,2)}ctx.textAlign='left';ctx.fillStyle='#b994ff';ctx.font='bold 23px sans-serif';ctx.fillText('ORBIT 2.0 / 星际成绩单',75,100);ctx.fillStyle='#f6f3ed';ctx.font='900 66px sans-serif';ctx.fillText('地球歪了 2.0',75,213);ctx.font='30px sans-serif';ctx.fillStyle='#b4afc7';ctx.fillText('桃桃想回家，宇宙不太配合。',75,278);window.TiltRenderer.drawMascot(ctx,745,155,85,{elapsed:1,vx:40});ctx.fillStyle='#d9ff70';ctx.font='900 200px sans-serif';ctx.fillText(String(last.score),63,523);ctx.font='bold 32px sans-serif';ctx.fillText('分',76,590);ctx.fillStyle='#f6f3ed';ctx.font='36px sans-serif';ctx.fillText(`用时 ${last.elapsed.toFixed(1)} 秒 / 星星 ${last.stars} 颗`,75,686);ctx.strokeStyle='#625174';ctx.setLineDash([8,10]);ctx.beginPath();ctx.moveTo(75,744);ctx.lineTo(825,744);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#d9ff70';ctx.beginPath();ctx.roundRect(75,810,750,115,24);ctx.fill();ctx.fillStyle='#202619';ctx.font='bold 35px sans-serif';ctx.fillText('不服？点挑战链接，把地球转明白。',100,882);ctx.fillStyle='#b994ff';ctx.font='25px sans-serif';ctx.fillText('120秒六关 · 手机电脑打开就玩',75,1020);ctx.fillStyle='#91869e';ctx.font='19px sans-serif';ctx.fillText('把战绩图和挑战链接一起发给朋友',75,1080);c.toBlob(blob=>{if(!blob){toast('图片生成失败，请重试');return}const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='地球歪了-'+last.score+'分.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('战绩图已生成，再复制挑战链接一起发')},'image/png')}
$('start').onclick=()=>{if(paused){paused=false;game.resume();$('intro').hidden=true;$('brake').disabled=false;return}start()};$('again').onclick=start;$('restart').onclick=()=>{game.stop();start()};$('share').onclick=share;$('save').onclick=card;$('sound').onclick=()=>{muted=!muted;$('sound').textContent='声音 '+(muted?'关':'开');$('sound').setAttribute('aria-label',muted?'开启声音':'关闭声音');$('sound').setAttribute('aria-pressed',String(!muted));sound('start')};$('new-map').onclick=()=>{seed=(Date.now()^Math.floor(Math.random()*4294967295))>>>0||1;target=null;last=null;history.replaceState(null,'',location.pathname+'?seed='+seed);challenge();$('intro').hidden=false;$('result').hidden=true;$('start').innerHTML='出发，带桃桃回家 <span>↗</span>';$('score').textContent='0000';$('time').textContent='120.0';$('stars').textContent='✦ 0';$('status').textContent='一张新地图 · 新的重力谜题';toast('新重力地图准备好了')};challenge();
window.addEventListener('resize',()=>game.resize());
let paused=false;
function updateMission(s){$('lives').textContent='♥ '.repeat(Math.max(0,s.lives??3))+'♡ '.repeat(Math.max(0,3-(s.lives??3)));$('lives').setAttribute('aria-label','剩余'+(s.lives??3)+'颗生命');$('energy-fill').style.transform='scaleX('+Math.max(0,Math.min(1,(s.energy??100)/100))+')';$('level-name').textContent=String(s.level||1).padStart(2,'0')+' / '+(s.levelName||'引力初学');$('level-hint').textContent=s.levelHint||'按住左右半屏，改变重力';[...$('level-track').children].forEach((e,i)=>{e.className=i+1<(s.level||1)?'done':i+1===(s.level||1)?'current':''})}
function brake(active){game.setBrake(active);$('brake').classList.toggle('held',active)}
$('brake').addEventListener('pointerdown',e=>{if(!playing)return;e.preventDefault();$('brake').setPointerCapture(e.pointerId);brake(true)});for(const t of ['pointerup','pointercancel','lostpointercapture'])$('brake').addEventListener(t,()=>brake(false));
$('help').onclick=()=>$('guide').showModal();$('close-guide').onclick=()=>$('guide').close();$('guide').addEventListener('click',e=>{if(e.target===$('guide'))$('guide').close()});
const portrait=$('mascot');window.TiltRenderer.drawMascot(portrait.getContext('2d'),280,155,102,{elapsed:1.2,vx:35,vy:0});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!paused){game.pause();paused=true;brake(false);$('brake').disabled=true;$('intro').hidden=false;$('start').innerHTML='继续这次航行 <span>↗</span>';}});
})();
